version: "3.7"

services:
    n8n:
        image: n8nio/n8n
        restart: always
        ports:
            - "5678:5678"
        environment:
            - GENERIC_TIMEZONE=America/New_York
            - WEBHOOK_URL=
        volumes:
            - ./n8n_data:/home/node/.n8n
